### ISSUE TITLE
not working at user signup

### ISSUE THREAD

**Issue by j2l** [saltcorn/captcha#1]
When not filling the captcha
```
error: invalid input syntax for type boolean: ""
    at Parser.parseErrorMessage (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

When filling the captcha
```
error: invalid input syntax for type boolean: "hjp6"
    at Parser.parseErrorMessage (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

in my custom form:
![image](https://user-images.githubusercontent.com/65325/205337178-0dae11e5-73f9-4814-b729-87dbc446ea5a.png)

**Comment by glutamate** [comment]
Thanks, I was hoping someone would test with sign up. This may be related to the other issue you saw, I will look at both

**Comment by j2l** [comment]
Looks like I'm a bug magnet. Usually at my first try I'm already at an edge case :sweat_smile:

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/pull/1508. Make sure you upgrade the captcha plugin to latest version

**Comment by j2l** [comment]
Great! Thanks @glutamate
